%% run h_... to "% Run to here for the forces" before this script
%% Gives the flow generated by the fluid at the boundary due to the stokeslets

% Loop over the whole space.

Ux = zeros(Nstoks,1);
Uy = zeros(Nstoks,1);

dy = (stks(2,2)-stks(1,2))/2;

for n1 = 1:Nstoks

    p = [stks(n1,1),stks(n1,2)+dy]; % Get the position of consideration, i and j done make sense to me here??

    for n = 1:Nstoks

        pN = stks(n,:); % Get the position of stokeslet N.
        Ftemp = F(n,:); % Get the forces of stokeslet N.
        r = sqrt(norm(p - pN).^2 + eps^2) + eps; % Distance, considered to stokeslet N.
        rho = (r+eps)/(r*(r-eps)); % Rho, considered to stokeslet N.

        for k = 1:2
            for l = 1:2
                Stemp(k,l) = -(log(r)-eps*rho)*(k==l) + (p(k)-pN(k))*(p(l)-pN(l))*rho/r;
            end
        end

        U = Stemp*Ftemp';
        Ux(n1) = Ux(n1) + U(1);
        Uy(n1) = Uy(n1) + U(2);

    end
end

n = 10;

x = linspace(-Xma/2,Xma/2,Npts); % X-values of solution space.
y = linspace(-Yma/2,Yma/2,Npts); % Y-values of solution space.

Uxtemp = Ux + Uflow(1);
Uytemp = Uy + Uflow(2);

scatter(stks(:,1),stks(:,2),2,'r')
n=1;
quiver(stks(1:n:end,1),stks(1:n:end,2),Uxtemp,Uytemp)
axis equal